version: '3'

services:
  build:
    image: microsoft/aspnetcore-build
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore ./web.csproj && dotnet publish ./web.csproj -c Release -o ./obj/Docker/publish"